apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-envs
  namespace: default
spec:
  provider: azure
  parameters:
    keyvaultName: cookiex-open-key-vault
    tenantId: 5aba969e-efd8-451c-8e72-cbc6c9ff1353
    useVMManagedIdentity: "true"
    userAssignedIdentityID: edc614fb-4471-484d-8268-9a2dcce12eb4
    objects: |
      array:
        - |
          objectName: mongodb-uri
          objectType: secret
        - |
          objectName: redis-host-name
          objectType: secret
        - |
          objectName: redis-primary-password
          objectType: secret
        - |
          objectName: classifier-secret
          objectType: secret
        - |
          objectName: open-cookies-csv-url
          objectType: secret
        - |
          objectName: open-trackers-csv-url
          objectType: secret
        - |
          objectName: openai-api-key
          objectType: secret
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - key: MONGODB_URI
          objectName: mongodb-uri
        - key: REDIS_HOST_NAME
          objectName: redis-host-name
        - key: REDIS_PRIMARY_PASSWORD
          objectName: redis-primary-password
        - key: CLASSIFIER_SECRET
          objectName: classifier-secret
        - key: OPEN_COOKIES_CSV_URL
          objectName: open-cookies-csv-url
        - key: OPEN_TRACKERS_CSV_URL
          objectName: open-trackers-csv-url
        - key: OPENAI_API_KEY
          objectName: openai-api-key
