apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookie-classifier-k8s
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookie-classifier-k8s
  template:
    metadata:
      labels:
        app: cookie-classifier-k8s
        app.kubernetes.io/name: cookie-classifier-k8s
    spec:
      containers:
      - name: cookie-classifier
        image: cookiexopen.azurecr.io/cookie-classifier:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: app-secrets
        env:
        - name: REQUESTS
          value: "5"
        - name: TIME
          value: "60"
        volumeMounts:
        - name: secrets-store-inline
          mountPath: /mnt/secrets
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-keyvault-envs