# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cookie-classifier-staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://stageing.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5616bcda4b5c4c96850b18702a2a2967 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f4e3300f3e4b427c85b01780dcedff41 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: stageing.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5616bcda4b5c4c96850b18702a2a2967 }}/cookie-classifier:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cookie-classifier-staging'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_525231094b9e4079ae9803672a6fb21b }}
        images: 'stageing.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5616bcda4b5c4c96850b18702a2a2967 }}/cookie-classifier:${{ github.sha }}'